import QtQuick
import Quickshell
import Quickshell.Io
import qs.config

QtObject {
    id: root

    function generate(Colors) {
        if (!Colors) return

        const fmt = (c) => c.toString()
        const toRgba = (c, a) => `rgba(${Math.round(c.r * 255)}, ${Math.round(c.g * 255)}, ${Math.round(c.b * 255)}, ${a})`
        const isDark = (c) => {
            const hex = fmt(c).replace("#", "")
            if (hex.length < 6) return true

            const red = parseInt(hex.slice(0, 2), 16)
            const green = parseInt(hex.slice(2, 4), 16)
            const blue = parseInt(hex.slice(4, 6), 16)
            if (Number.isNaN(red) || Number.isNaN(green) || Number.isNaN(blue)) return true

            return ((red * 299 + green * 587 + blue * 114) / 1000) < 128
        }

        const primary = fmt(Colors.primary)
        const onPrimary = fmt(Colors.overPrimary)
        const background = toRgba(Colors.background, Config.theme.srBg.opacity)
        const onBackground = fmt(Colors.overBackground)
        const surface = fmt(Colors.surface)
        const onSurface = fmt(Colors.overSurface)
        const surfaceContainer = fmt(Colors.surfaceContainer)
        const dark = isDark(Colors.background)
        const gtkTheme = dark ? "adw-gtk3-dark" : "adw-gtk3"
        const colorScheme = dark ? "prefer-dark" : "prefer-light"

        let css = "/* GTK Colors generated by Nonchalant */\n\n"
        
        css += `@define-color accent_color ${primary};\n`
        css += `@define-color accent_fg_color ${onPrimary};\n`
        css += `@define-color accent_bg_color ${primary};\n`
        css += `@define-color theme_selected_bg_color ${primary};\n`
        css += `@define-color theme_selected_fg_color ${onPrimary};\n`
        css += `@define-color theme_unfocused_selected_bg_color ${primary};\n`
        css += `@define-color theme_unfocused_selected_fg_color ${onPrimary};\n`
        css += `@define-color window_bg_color ${background};\n`
        css += `@define-color window_fg_color ${onBackground};\n`
        css += `@define-color headerbar_bg_color ${background};\n`
        css += `@define-color headerbar_fg_color ${onBackground};\n`
        css += `@define-color popover_bg_color ${surface};\n`
        css += `@define-color popover_fg_color ${onSurface};\n`
        css += `@define-color view_bg_color ${background};\n`
        css += `@define-color view_fg_color ${onBackground};\n`
        css += `@define-color card_bg_color ${surfaceContainer};\n`
        css += `@define-color card_fg_color ${onSurface};\n`
        
        // Sidebar typically matches window or has slight contrast. 
        // Using window variables as reference.
        css += `@define-color sidebar_bg_color @window_bg_color;\n`
        css += `@define-color sidebar_fg_color @window_fg_color;\n`
        css += `@define-color sidebar_border_color @window_bg_color;\n`
        css += `@define-color sidebar_backdrop_color @window_bg_color;\n\n`

        // Selection contrast rules: ensure item labels use onPrimary when selected
        css += `*:selected,\n`
        css += `selection,\n`
        css += `.view:selected,\n`
        css += `iconview:selected,\n`
        css += `.content-view .tile:selected,\n`
        css += `gridview > child:selected,\n`
        css += `flowbox > flowboxchild:selected,\n`
        css += `treeview.view:selected,\n`
        css += `row:selected {\n`
        css += `  background-color: @theme_selected_bg_color;\n`
        css += `  color: @theme_selected_fg_color;\n`
        css += `}\n\n`

        css += `*:selected label,\n`
        css += `*:selected .label,\n`
        css += `selection label,\n`
        css += `.view:selected label,\n`
        css += `iconview:selected label,\n`
        css += `.content-view .tile:selected label,\n`
        css += `gridview > child:selected label,\n`
        css += `flowbox > flowboxchild:selected label,\n`
        css += `treeview.view:selected label,\n`
        css += `row:selected label,\n`
        css += `iconview text:selected,\n`
        css += `.view text:selected,\n`
        css += `textview text:selected {\n`
        css += `  color: @theme_selected_fg_color;\n`
        css += `}\n\n`

        css += `/* Keep text/icons opaque; only ask GTK windows to draw translucent surfaces. */\n`
        css += `window,\n`
        css += `window.background,\n`
        css += `.background {\n`
        css += `  background-color: ${background};\n`
        css += `}\n`

        const home = Quickshell.env("HOME")
        const gtk3Dir = home + "/.config/gtk-3.0"
        const gtk4Dir = home + "/.config/gtk-4.0"

        writer.text = css
        
        // Write to GTK 3/4 and reload theme
        const cmd = `
            mkdir -p "${gtk3Dir}" "${gtk4Dir}" && \\
            cat <<'EOF' | tee "${gtk3Dir}/gtk.css" "${gtk4Dir}/gtk.css" "${gtk3Dir}/colors.css" "${gtk4Dir}/colors.css" > /dev/null
${css}
EOF
            gsettings set org.gnome.desktop.interface color-scheme '${colorScheme}' && \\
            gsettings set org.gnome.desktop.interface gtk-theme "" && \\
            gsettings set org.gnome.desktop.interface gtk-theme '${gtkTheme}'
        `
        
        writerProcess.command = ["sh", "-c", cmd]
        writerProcess.running = true
    }

    property QtObject writer: QtObject {
        id: writer
        property string text
    }

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("GtkGenerator: Colors generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: (err) => {
                if (err) console.error("GtkGenerator Error:", err)
            }
        }
    }
}
